return {
	create_tree = require("@self/tree/create_tree"),
	create_tree_from_string = require("@self/tree/create_tree_from_string"),
	traverse_tree = require("@self/tree/traverse_tree"),
	encode_symbols = require("@self/encoding/encode_symbols"),
	decode_symbols = require("@self/encoding/decode_symbols"),
	encode_string = require("@self/encoding/encode_string"),
	decode_string = require("@self/encoding/decode_string"),
}
